### PR TITLE
Dockerized the project with Dockerfile and docker-compose files

### PR DESCRIPTION
**Pull request by yourtechmafia**
- Created a **Dockerfile** to streamline the setup process, making it easier to deploy and run across different environments without the "it works on my machine" hassle.
- Created a **docker-compose** file to define the services, networks, and volumes for the application and its dependencies, like a MySQL database.
- Modified the _requirements.txt_ file to make _Flask_ (2.0.1) and _Werkzeug_ (2.0.1) compatible.

After installing [Docker](https://docs.docker.com/engine/install/) and [Docker Compose](https://docs.docker.com/compose/install/), launch the app with a single command - $ _docker-compose up_

### CODE REVIEW

**Comment by Kelvinskell** [comment]
Great work. However, the application is meant to connect to an RDS MySQL database. The terraform code ensures the creation of the database. This will make the RDS database created by terraform idle and redundant.

**Comment by Kelvinskell** [comment]
Also the "asg_userdata.sh" bash script in the terraform directory is unchanged. The bash script is configured to start the application n the instance. It has to be modified to integrate docker and abandon creating the unit file and runs the application.

**Comment by yourtechmafia** [comment]
> Great work. However, the application is meant to connect to an RDS MySQL database. The terraform code ensures the creation of the database. This will make the RDS database created by terraform idle and redundant.

Yeah, I understand. I believe not everyone who comes across this project might understand Terraform or want to use it. Peradventure a DevOps newbie or beginner with basic knowledge (just Docker and containerization) comes across this, it would be of great help to run the application with his limited knowledge first before anything else.

**Comment by Kelvinskell** [comment]
It raises an exception on registration or login: mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'yourdbname.user' doesn't exist

**Comment by Kelvinskell** [comment]
Great work. Modify the README.md if you  have the time. The update should include how to run the app standalone using docker compose.

**Pull request merged**
